### ISSUE TITLE
Consider updating fluentd to 1.x

### ISSUE THREAD

**Issue by StevenACoffman** [samsung-cnct/kraken-logging-fluentd-daemonset#9]
So now that fluent-bit reached 1.0 (and 1.1),  kubernetes/kubernetes#58525 is merged, it might be time to consider updating here as well.

**Comment by DStorck** [comment]
We have switched over to using fluent-bit for our logging so aren't really maintaining this anymore. https://github.com/samsung-cnct/chart-fluent-bit

**Comment by StevenACoffman** [comment]
Awesome. Thanks!
